apiVersion: v1
kind: Secret
metadata:
  name: blog-secrets
type: Opaque
stringData:
  SESSION_SECRET: "замените-длинной-случайной-строкой"
  ADMIN_USERNAME: "gera"
  ADMIN_PASSWORD: "замените-паролем"
